### ISSUE TITLE
invalid POST method says "Only GET or HEAD methods are supported"

### ISSUE THREAD

**Issue by freezeboy** [haskell-servant/servant#194]
Given the following API:
```haskell
type MyAPI = Get '[JSON] User
                   :<|> Post '[JSON] User Int
```

And if I send an invalid request with method POST (for example, I omit one field in the User definition), I get an error message from the Get handler.

My understanding is that the post fails silently, then we try the get handler and it of course also fails, but this time loudly.
This appears when one url accepts two methods.

**Comment by alpmestan** [comment]
1/ Are you sure the `Int` is meant to be there at the end of the API type def? I'll assume it's a typo.
2/ Is it with servant 0.4? I think it is, because it looks like a problem that we had in 0.4 and fixed in the upcoming release (and `master`) by having a proper routing machinery in place of the old hacky routing code we had. Can you try building your server against the *master* branch?

**Comment by freezeboy** [comment]
I tried with the latest master .. looks good now
sorry for the noise

**Comment by dmjio** [comment]
Still an issue for me, even after a 0.5 upgrade. Can we reopen?

**Comment by alpmestan** [comment]
Sure, can you provide us with a minimal repro for this bug that we can toy around with?

**Comment by dmjio** [comment]
@alpmestan yes, will do that soon

**Comment by dmjio** [comment]
@alpmestan @arianvp 
Here's my API Spec
```haskell
------------------------------------------------------------------------------                                                                                                    
-- | Post API                                                                                                                                                                     
type PostAPI =                                                                                                                                                                    
       "post"                                                                                                                                                                     
         :> Capture "postid" PostId                                                                                                                                               
         :> Header "X-Access-Token" JWT.JSON                                                                                                                                      
         :> Get '[JSON] Post                                                                                                                                                      
  :<|> "post"                                                                                                                                                                     
         :> Capture "postid" PostId                                                                                                                                               
         :> "comment"                                                                                                                                                             
         :> "count"                                                                                                                                                               
         :> Header "X-Access-Token" JWT.JSON                                                                                                                                      
         :> Get '[JSON] CommentCount                                                                                                                                              
  :<|> "post"                                                                                                                                                                     
         :> Capture "postid" PostId                                                                                                                                               
         :> ReqBody '[JSON] PostBodyUpdate                                                                                                                                        
         :> Header "X-Access-Token" JWT.JSON                                                                                                                                      
         :> Put '[JSON] Post                                                                                                                                                      
  :<|> "post"                                                                                                                                                                     
         :> ReqBody '[JSON] NewPostJSON                                                                                                                                           
         :> Header "X-Access-Token" JWT.JSON                                                                                                                                      
         :> S.Post '[JSON] Post                                                                                                                                                   
  :<|> "post"                                                                                                                                                                     
         :> Capture "postid" PostId                                                                                                                                               
         :> Header "X-Access-Token" JWT.JSON                                                                                                                                      
         :> Delete '[JSON] () 
```
Here's the curl
```bash
λ Davids-MacBook-Pro-2 Vertigo-Social → λ git integration → curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{
  \"long\": 0,
  \"body\": \"string\",
  \"lat\": 0,
  \"contentid\": \"string\",
  \"type\": \"broadcast\"
}" "http://localhost:8000/post"
Only GET or HEAD is supported%      
```
Occurs on `0.4.4` and `0.5`

**Comment by freezeboy** [comment]
Thanks, could you please provide the 'NewPostJSON' structure
Or is it only the fact that the JWT is missing ?

**Comment by dmjio** [comment]
Ah, sorry, even when including the JWT header it still says the same. @freezeboy 

```bash
[nix-shell:~/Documents/Work/Vertigo/Vertigo-Social]$ curl -X POST --header "X-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0NDA2ODk1NTEsIlVzZXJJZCI6IjllZWFjNmRiLWIxNzgtNDU1MS1hMTA3LWVhNmUxMzBlMzkwZiIsImlhdCI6MTQ0MDY2MDc1MSwic3ViIjoiYWxleGsiLCJFbWFpbCI6ImFsZXhhbmRlcl93b3JrQGJrLnJ1In0.Nz9miz7MhlY9pCuOTeRFdL_m_JjQ0DWbJ0o8n1cgtkQ" -d "{
  \"long\": 0,
  \"body\": \"string\",
  \"lat\": 0,
  \"contentid\": \"string\",
  \"userid\": \"string\",
  \"repostid\": \"string\",
  \"type\": \"broadcast\"
}" "http://localhost:8000/post"
Only GET or HEAD is supported
```

The JSON structure varies depending on the presence of the `repostid` field. 
```haskell
------------------------------------------------------------------------------                                                                                                    
-- | New Post JSON                                                                                                                                                                
data NewPostJSON = NewRePostId PostId | NewPostBody NewPost                                                                                                                       
  deriving (Show)      
------------------------------------------------------------------------------                                                                                                    
-- | FromJSON NewPost                                                                                                                                                          
instance FromJSON NewPost where                                                                                                                                                   
  parseJSON (Object o) =                                                                                                                                                          
    NewPost <$> o .: "type"                                                                                                                                                       
            <*> o .: "contentid"                                                                                                                                                  
            <*> o .: "body"                                                                                                                                                       
            <*> o .:? "long"                                                                                                                                                      
            <*> o .:? "lat"                                                                                                                                                       
  parseJSON x = typeMismatch "New Post" x  
------------------------------------------------------------------------------                                                                                                    
-- | `FromJSON` instance for `NewPost`                                                                                                                                            
instance FromJSON NewPostJSON where                                                                                                                                               
    parseJSON x@(Object o) = do                                                                                                                                                   
      result :: Maybe PostId <- o .:? "repostid"                                                                                                                                  
      case result of                                                                                                                                                              
        Just rpid -> pure $ NewRePostId rpid                                                                                                                                      
        Nothing   -> NewPostBody <$> parseJSON x                                                                                                                                  
    parseJSON value = typeMismatch "Invalid Post creation type" value  

```

**Comment by dmjio** [comment]
UPDATE: This does not appear to be a problem with servant per se, but more likely a user error. It most likely deals with 
```haskell
ReqBody '[JSON] NewPostJSON
```

**Comment by dmjio** [comment]
So, it looks like the problem was that the json failed parsing, but because the api is defined as 
```haskell
type WholeAPI = API :<|> Raw
``` 
The parse failure caused the router to redirect to `Raw` instead of failing with JSON info. How this should have been handled is a topic of discussion.

**Comment by domenkozar** [comment]
I've hit this as well, quite bad UX.

**Comment by t3hmrman** [comment]
Just noting I ran into this today as well, glad this ticket was here to set me on the right path.

**Comment by arianvp** [comment]
Is there something we can do in terms of documentation to make this behaviour more clear?

**Comment by t3hmrman** [comment]
Hi @arianvp I'm not sure... It's a thorny problem because it *only* shows up when you have some API combined with a raw server (which I happen to have) -- but maybe a page in the cookbook (or a different section all together) could be used for common errors?
